### ISSUE TITLE
[Jenkins] CLUE ASAN 배포 파이프라인

### ISSUE THREAD

**Issue by yunsangr** [linewalks/be-common#36]
# 내용
아산 배포시 사용되는 tar 파일들을 원하는 배포자의 컴퓨터로 전달합니다.

- http://192.168.0.21:8888/job/CDM/job/Asan/ 젠킨스 폴더에서 작업합니다.
- http://192.168.0.21:8888/job/EXI/job/AKMD/ EXI 에서 구현된 파이프라인들을 참고합니다.

- 사전 과업으로 설정파일을 이미지에 포함하지 않고 이미지를 생성하고 컨테이너 구동시 설정파일들을 마운트해서 읽게 수정합니다.
아래 [컴포즈 파일](http://192.168.0.21:8888/job/EXI/job/AKMD/configfiles/)을 참고합니다.
```yaml
  api:
    image: exi-api-master:latest
    volumes:
      - ./exi-api-master-env.cfg:/MDwalks-EXI/main/env.cfg           <-- 설정 파일 마운트
    entrypoint: bash bin/run_server.sh 5000
    ports:
      - 5000:5000
    depends_on:
      - redis
  background_worker:
    image: exi-api-master:latest
    volumes:
      - ./exi-api-master-env.cfg:/MDwalks-EXI/main/env.cfg.          <-- 설정 파일 마운트
    entrypoint: bash bin/start_celery.sh
    depends_on:
      - redis
```

구현하게 될 파이프라인 설명:
 - [CLUE API](http://192.168.0.21:8888/job/CDM/job/Asan/job/CLUE%20API/)
   - CLUE-API 최선 소스 코드를 받아 이미지를 생성하고 tar 파일로 젠킨스에 archive 합니다.
 - [CLUE Client](http://192.168.0.21:8888/job/CDM/job/Asan/job/CLUE%20Client/)
   - CLUE-Client 최선 소스 코드를 받아 이미지를 생성하고 tar 파일로 젠킨스에 archive 합니다.
- [CLUE CDN](http://192.168.0.21:8888/job/CDM/job/Asan/job/CLUE%20CDN/)
   - CLUE-CDN 최선 소스 코드를 받아 이미지를 생성하고 tar 파일로 젠킨스에 archive 합니다.
 - [CLUE LOGIN](http://192.168.0.21:8888/job/CDM/job/Asan/job/CLUE%20LOGIN/)
   - CLUE-LOGIN 최선 소스 코드를 받아 이미지를 생성하고 tar 파일로 젠킨스에 archive 합니다.
- [CLUE Extractor](http://192.168.0.21:8888/job/CDM/job/Asan/job/CLUE%20Extractor/)
  - CLUE-Extractor 최선 소스 코드를 받아 이미지를 생성하고 tar 파일로 젠킨스에 archive 합니다.
 - [Send Artifacts](http://192.168.0.21:8888/job/CDM/job/Asan/job/Send%20Artifacts/)
   - `CLUE-API/Client/Extracotor` 파이프라인을 통해 생성된 tar 파일들을 불러와 필요한 모든 파일을 하나의 `package.tar` 로 만들어서 원하는 호스트 서버에 전송합니다. 
 - [Trigger All Pipelines](http://192.168.0.21:8888/job/CDM/job/Asan/job/Trigger%20All%20Pipelines/)
   - `CLUE-API/Client/Extracotor` 파이프라인을 한 번에 동작하게 합니다.
