### ISSUE TITLE
[Kubernetes] Deploy CLUE with Kong A-Z

### ISSUE THREAD

**Issue by yunsangr** [linewalks/be-common#41]
### 내용

쿠버네티스 단일 클러스터를 지원해주는 `minikube` 와 패키지 매니저 역할을 하는 `helm` 을 사용해서 `kong`/`konga` 를 배포하고 `CLUE` 프로젝트 배포합니다. 

### 절차 

1. `minikube` 설치
2. `minikube` 구동 및 `dashboard` 접근
3. `helm` 설치
3. `kong` 와 `konga` charts 를 `helm` 통해서 설치
4. `minikube` 에 이미지 로드
5. `kompose` 을 사용해서 `CLUE` 배포
6.  `konga` 를 통한 Gateway 설정

### Minikube 설치 
- [Install minikube(offical doc)](https://minikube.sigs.k8s.io/docs/start/)
- 위 링크를 참고해서 해당하는 OS 및 설정들을 맞추어 설치합니다. (아래 예시 참고)
```sh
> curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
> sudo install minikube-linux-amd64 /usr/local/bin/minikube
```

### Minikube 구동 및 Dashboard 접근
쿠버네티스 명령어 도구인 kubectl 을 설치합니다. [설치 문서](https://kubernetes.io/ko/docs/tasks/tools/install-kubectl-linux/)
```sh
> minikube start
😄  minikube v1.23.2 on Ubuntu 20.04
🆕  Kubernetes 1.22.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.22.2
> minikube dashboard --url
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
> kubectl proxy --address='0.0.0.0' --disable-filter
W1007 14:21:20.709411 3707253 proxy.go:162] Request filter disabled, your proxy is vulnerable to XSRF attacks, please be cautious
Starting to serve on [::]:8001
```
아래 주소를 참고하여 접속합니다.
> http://<YOUR_HOST_IP>:8001/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/#/workloads?namespace=default

### Helm 설치
`Helm`은 쿠버네티스에서 여러가지 기능을 사용하는데 필요한 yml 파일들을 정해진 형식에 의해서(Charts) 이미 구현되어있는 프로젝트를 불러와 사용하게 해주는 패키지 매니져입니다.
[Helm Installation](https://helm.sh/docs/intro/install/) 문서를 참고하여 설치합니다.

> Helm version 을 반드시 3.x 버젼으로 통일합니다.

### Kong/Konga Charts 를 Helm 통해서 설치
쿠버네티스에서 Kong Ingress Controller 를 설치하기 위해서는 여러가지 yml 파일들을 작성해야하는데 이는 복잡하고 시간이 오래 걸리는 작업입니다. 이를 해결하기 위해 이미 구현된 Kong/Konga Charts 를 사용해서 설치를 하도록 합니다.

- [Kong charts](https://github.com/Kong/charts)
- [Konga charts](https://github.com/pantsel/konga)

#### Kong chart

Kong helm chart 를 받아옵니다.
```sh
> helm repo add kong https://charts.konghq.com
> helm repo update
```

Kong 을 설치하기 위해서 설정해주야하는 변수 값들이 있습니다. 아래를 참고합니다.

- admin 설정
  - konga 에 admin-url 를 제공해주어햐 하기 때문에 필요한 설정
- env 설정
  - kong 배포시 필요한 데이터베이스 환경 설정
- postgresql
  - konga 사용하기 위해서 반드시 db-mode로 kong 을 설치해야합니다.
  - kong 배포시 사용되는 postgresql sub charts 설정

위 설정값들은 `kong_values.yaml`에 yaml 형식으로 저장됩니다.
```yml
env:
  database: postgres            # db postgresql 지정
  pg_database: kong             # psql db 이름 설정
  pg_user: kong                 # psql db 유저 이름 설정 
  pg_password: kong             # psql db 유저 비밀번호 설정

admin:
  enabled: true                 # kong admin 활성화
  http:
    enabled: true               # kong admin http 활성화
  tls: 
    enabled: true               # kong admin tls 활성화

postgresql:
  enabled: true                 # sub charts postgresql 사용 선언 
  postgresqlDatabase: kong      # sub charts postgresql database 설정
  postgresqlUsername: kong      # sub charts postgresql username 설정
  postgresqlPassword: kong      # sub charts postgresql password 설정

ingressController:
  installCRDs: false            # ingress controller CRD 설치 여부
```
`kong_values.yaml` 저장된 값들을 설정하여 kong 을 설치합니다.
```sh
> helm install my-release kong/kong -f kong_values.yaml
```

#### Konga chart

Konga chart github repository 를 받아오고 chart 경로에 가서 실행합니다.
```sh
> git clone https://github.com/pantsel/konga.git
> cd charts/konga
> helm install konga ./ 
```
konga 를 실행한 Pod 이름을 `POD_NAME` 에 저장하고 해당 팟을 외부에서 접근 가능하게 port-forward 를 해줍니다.
> remote 접근이 가능하게 하기 위해 `--address 0.0.0.0` 옵션을 반드시 포함합니다.
```sh
> export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=konga,app.kubernetes.io/instance=konga" -o jsonpath="{.items[0].metadata.name}")
> kubectl port-forward --address 0.0.0.0 $POD_NAME 8080:1337
```
아래의 주소로 Konga Dashboard 를 접근합니다.
- http://192.168.0.???:8080/#!/dashboard
### Minikube 에 이미지 로드
쿠버네티스가 읽을수 있는 클러스터 내부에 이미지를 로드해줍니다.

```sh
> minikube image load mdwalks_clue_api
> minikube image load mdwalks_clue_client
> minikube image list                                         # 이미지가 정상적으로 로드되었는지 확인합니다.
```

### Kompose 을 사용한 `CLUE` 배포

`Kompose` 는 `docker-compose.yml` 파일의 내용을 쿠버네티스가 이해할수있는 yml 파일의 형식으로 자동으로 변환해줍니다.

```sh
> sudo snap install kompose # snap 을 사용해 kompose 설치
> kompose convert -f docker-compose.yml --out docker-kompose.yml # docker-compose.yml -> docker-kompose.yml로 전환
> kubectl apply -f docker-kompose.yml                           
service/api created
...
deployment.apps/redis created
```
- `docker-compose.yml`: https://github.com/linewalks/be-common/issues/41#issuecomment-977639115
-  `clue-kompose.yml`: https://github.com/linewalks/be-common/issues/41#issuecomment-977639873

### Konga UI 를통한 Gateway 설정
konga UI 에 접속하여 아래 두 가지 방법중 하나로 Gateway routes 를 설정합니다. 
- 직접 게이트웨이 설정
- 기존에 생성된 `snapshot.json`  을 사용해서 설정
   - `initial-snapshot.json`: https://github.com/linewalks/be-common/issues/41#issuecomment-978927532

**Comment by yunsangr** [comment]
## docker-comopse.yml for CLUE

```yml
version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  api:
    image: "mdwalks_clue_api_develop:126"
    entrypoint: bash bin/run_server.sh 8000
    expose:
      - 8000
    depends_on:
      - redis
    volumes:
      - web:/mdwalks_clue/files
  converter_worker:
    image: "mdwalks_clue_api_develop:126"
    entrypoint: bash bin/start_celery_converter_worker.sh
    depends_on:
      - redis
    volumes:
      - web:/mdwalks_clue/files
  extractor_worker:
    image: "mdwalks_clue_api_develop:126"
    entrypoint: bash bin/start_celery_extractor_worker.sh
    depends_on:
      - redis
  generator_worker:
    environment:
      - C_FORCE_ROOT=true
    image: "mdwalks_clue_api_develop:126"
    entrypoint: bash bin/start_celery_generator_worker.sh
    depends_on:
      - redis
  batch_worker:
    image: "mdwalks_clue_api_develop:126"
    entrypoint: bash bin/start_celery_batch_worker.sh
    depends_on:
      - redis
  client:
    image: "mdwalks_clue_client_develop:176"
    expose:
      - 3000
    depends_on: 
      - api
    labels:
      kompose.service.type: nodeport
volumes:
  web:

```

**Comment by yunsangr** [comment]
## clue-kompose.yml for CLUE
```yml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: api
    name: api
  spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    selector:
      io.kompose.service: api
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.service.type: nodeport
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: client
    name: client
  spec:
    ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    selector:
      io.kompose.service: client
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: redis
    name: redis
  spec:
    ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    selector:
      io.kompose.service: redis
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: api
    name: api
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: api
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: api
      spec:
        containers:
        - command:
          - bash
          - bin/run_server.sh
          - "8000"
          image: mdwalks_clue_api_develop:126
          imagePullPolicy: ""
          name: api
          ports:
          - containerPort: 8000
          resources: {}
          volumeMounts:
          - mountPath: /mdwalks_clue/files
            name: web
        restartPolicy: Always
        serviceAccountName: ""
        volumes:
        - name: web
          persistentVolumeClaim:
            claimName: web
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: web
    name: web
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: batch-worker
    name: batch-worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: batch-worker
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: batch-worker
      spec:
        containers:
        - command:
          - bash
          - bin/start_celery_batch_worker.sh
          image: mdwalks_clue_api_develop:126
          imagePullPolicy: ""
          name: batch-worker
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.service.type: nodeport
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: client
    name: client
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: client
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.service.type: nodeport
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: client
      spec:
        containers:
        - image: mdwalks_clue_client_develop:176
          imagePullPolicy: ""
          name: client
          ports:
          - containerPort: 3000
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: converter-worker
    name: converter-worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: converter-worker
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: converter-worker
      spec:
        containers:
        - command:
          - bash
          - bin/start_celery_converter_worker.sh
          image: mdwalks_clue_api_develop:126
          imagePullPolicy: ""
          name: converter-worker
          resources: {}
          volumeMounts:
          - mountPath: /mdwalks_clue/files
            name: web
        restartPolicy: Always
        serviceAccountName: ""
        volumes:
        - name: web
          persistentVolumeClaim:
            claimName: web
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: web
    name: web
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: extractor-worker
    name: extractor-worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: extractor-worker
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: extractor-worker
      spec:
        containers:
        - command:
          - bash
          - bin/start_celery_extractor_worker.sh
          image: mdwalks_clue_api_develop:126
          imagePullPolicy: ""
          name: extractor-worker
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: generator-worker
    name: generator-worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: generator-worker
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: generator-worker
      spec:
        containers:
        - command:
          - bash
          - bin/start_celery_generator_worker.sh
          env:
          - name: C_FORCE_ROOT
            value: "true"
          image: mdwalks_clue_api_develop:126
          imagePullPolicy: ""
          name: generator-worker
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        --out clue-kompose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: redis
    name: redis
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: redis
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            --out clue-kompose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: redis
      spec:
        containers:
        - image: redis:alpine
          imagePullPolicy: ""
          name: redis
          ports:
          - containerPort: 6379
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}


```
